### ISSUE TITLE
how to close popup window

### ISSUE THREAD

**Issue by ukadmin** [kentwinder/WebView-Optimization#1]
Hello, thank you for sharing your code. But can you tell me how to close the popup windows? This would be very nice :)

**Comment by kentwinder** [comment]
My solution is to open url of pop up window inside current web view.
So, if you want to close it, I think you can display web view toolbar on the bottom of the web view so user can go back/forward inside web view or implement gesture for back/forward action

**Comment by ukadmin** [comment]
thank you for your answer. I only need a close tab in the popup window, but i don't know much about swift programming :)

**Comment by kentwinder** [comment]
Sorry, but I don't get the part where you want to `close tab in the popup window`. Can you please give me more details about that?

**Comment by ukadmin** [comment]
I don't know much about Swift and code but you declare _blank to open in a Popup. Maybe there is a way to let open it in new view and add a close button or a navigation bar in xcode.

**Comment by piqsys** [comment]
Hi kentwinder, thanks for share, I have learned a lot reading your code. 

thanks, now y have the same   or similar query,  perhaps you can help me?, if I show pdf file in webview, only in this case, how I can detect and put close button or redirect to main web url in the secondary viewcontroller.

Thanks for all. Good job.
