### ISSUE TITLE
Can't close window when multiple window are opened.

### ISSUE THREAD

**Issue by Jennis2412** [kentwinder/WebView-Optimization#2]
Kindly read the thread which I have uploaded on stackoverflow:

https://stackoverflow.com/questions/58056731/why-window-close-is-not-working-for-multiple-windows

For your convenience I'm again describing the issue here.

I have give webview to "www.someUrl.com". This website has code of window.open("some_valid_url") and window.close() to close the opened window.

Consider the following case, when we do operation in following order, I cannot close the window:

Main Page --> Main Page opens window A --> Then window A opens window B.

If you close window B, then try to close window A. Window A is not closed. Hence cannot return to main page. For single window the code is working perfect. 

The code which is used to open and close windows respectively is as follows :

```
class ViewController: UIViewController, UIWebViewDelegate, CLLocationManagerDelegate,WKUIDelegate,WKNavigationDelegate
{
    @IBOutlet weak var webView: WKWebView!
    var popupWebView: WKWebView?
    ...

    func webView(_ webView: WKWebView, createWebViewWith configuration: WKWebViewConfiguration, for navigationAction: WKNavigationAction, windowFeatures: WKWindowFeatures) -> WKWebView? {
            popupWebView = WKWebView(frame: view.bounds, configuration: configuration)
            popupWebView!.autoresizingMask = [.flexibleWidth, .flexibleHeight]
            popupWebView!.navigationDelegate = self
            popupWebView!.uiDelegate = self
            view.addSubview(popupWebView!)
            return popupWebView!
        }

    func webViewDidClose(_ webView: WKWebView) {
        if webView == popupWebView {
            popupWebView?.removeFromSuperview()
            popupWebView = nil
        }
    }
    ...
}
```

Here I have only shared the code which is used to open and close the window.
Please ask if you need any further details.

**Comment by kentwinder** [comment]
Hi Jennis,
I will take a look at this problem in a few days because right now I'm on a business trip, I will get back to you soon,

**Comment by kentwinder** [comment]
Oh, you already found the solution for this, I just checked and it actually works.
Thank you so much for your contribution.
Have a nice day ^^

**Comment by Jennis2412** [comment]
Hi kentwinder,

Thanks for the reply. I founded the answer to the question the yesterday(24th Sept 2019). I was about to post it here also.
But I ran into another problem after solving the window issue.
When app goes to background and comes to again to foreground and then try to encounter window.open the window opened is about:blank, not the URL to be opened.

I think that this not related to ```createWebViewWith configuration``` or ```webViewDidClose``` .

I do understand this might be an of topic discussion .

So, is there any solution to my another problem?
Or any hint what might be causing this issue, Because I'm not able to find any solution related to this problem.

**Comment by kentwinder** [comment]
I'm not so sure about that, but after checking with my demo project, it has no problem opening popup/window after coming from the background :(

**Comment by Jennis2412** [comment]
Thanks for the reply kentwinder, I do understand that the issue is not reproducible. I also checked in your project, your project works as smooth butter. Thanks for the reply though. :)

**Comment by kentwinder** [comment]
If there is anything that I can help, don't hesitate to ask, it's my pleasure

**Comment by Jennis2412** [comment]
It would be great if you can throw some light on background/foreground issue. I tried printing url when app comes from background with the help of ```webview.url``` inside ```createWebViewWith configuration``` delegate, And it prints the desired URL, but still it opens about:blank after coming to foreground. 

Any help would be greatly appreciated. 

Debugging is also not helping me to solve the issue.
